#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

blockMesh &> log.blockMesh

gdb -q -x debug/config --args Test-findSphere 

#------------------------------------------------------------------------------
